"""Generate checked-in L8 protocol metadata and typed marshalling declarations."""
from pathlib import Path
import xml.etree.ElementTree as ET
import sys

ROOT = Path(__file__).resolve().parent
interfaces = [i for f in ('wayland.xml', 'xdg-shell.xml', 'xdg-decoration-unstable-v1.xml')
              for i in ET.parse(ROOT / 'protocol' / f).getroot().findall('interface')]
out = ['tag wayland;\n\nimport "types.l8";\nwl_null_interface: ?*WLInterface = null;\n', '// Generated by generate.py from the vendored protocol XML; do not edit.\n']
letters = dict(int='i', uint='u', fixed='f', string='s', object='o', new_id='n', array='a', fd='h')
for i in interfaces:
    out.append(f'{i.get("name")}_interface: WLInterface = WLInterface {{ name: "{i.get("name")}", version: {i.get("version")}i32, method_count: {len(i.findall("request"))}i32, methods: null, event_count: {len(i.findall("event"))}i32, events: null }};')
for interface in interfaces:
    name = interface.get('name')
    for kind in ('request', 'event'):
        messages = interface.findall(kind)
        for n, msg in enumerate(messages):
            args = msg.findall('arg')
            if args:
                values = []
                for a in args:
                    if a.get('type') == 'new_id' and not a.get('interface'):
                        values.extend(['wl_null_interface', 'wl_null_interface'])
                    values.append('(&' + a.get('interface') + '_interface) as ?*WLInterface' if a.get('interface') else 'wl_null_interface')
                out.append(f'{name}_{kind}_{n}_types: [{len(values)}]?*WLInterface = [{", ".join(values)}];')
        if messages:
            out.append(f'{name}_{kind}s: [{len(messages)}]WLMessage = [')
            for n, msg in enumerate(messages):
                sig = str(msg.get('since')) if int(msg.get('since', '1')) > 1 else ''
                for a in msg.findall('arg'):
                    if a.get('type') == 'new_id' and not a.get('interface'):
                        sig += 'su'
                    sig += ('?' if a.get('allow-null') == 'true' else '') + letters[a.get('type')]
                types = f'&{name}_{kind}_{n}_types[0]' if msg.findall('arg') else 'null'
                out.append(f'    WLMessage {{ name: "{msg.get("name")}", signature: "{sig}", types: {types} }}' + (',' if n + 1 < len(messages) else ''))
            out.append('];')
    requests, events = interface.findall('request'), interface.findall('event')

out.append('wl_protocol_init() {')
for i in interfaces:
    for kind in ('request', 'event'):
        if i.findall(kind):
            field = 'methods' if kind == 'request' else 'events'
            out.append(f'    {i.get("name")}_interface.{field} = &{i.get("name")}_{kind}s[0];')
out.append('}\n')


selected = {'zxdg_decoration_manager_v1': ['destroy', 'get_toplevel_decoration'], 'zxdg_toplevel_decoration_v1': ['destroy', 'set_mode'], 'wl_display': ['get_registry'], 'wl_registry': [],
 'wl_compositor': ['create_surface'], 'wl_surface': ['destroy', 'attach', 'damage', 'frame', 'commit'],
 'wl_seat': ['get_keyboard', 'get_pointer', 'release'], 'wl_keyboard': ['release'], 'wl_pointer': ['set_cursor','release'],
 'xdg_wm_base': ['destroy','get_xdg_surface','pong'], 'xdg_surface': ['destroy','get_toplevel','ack_configure'],
 'xdg_toplevel': ['destroy','set_title','set_app_id','set_min_size']}
for interface in interfaces:
    name = interface.get('name')
    for opcode, msg in enumerate(interface.findall('request')):
        method = msg.get('name')
        if method not in selected.get(name, []):
            continue
        prefix = name + '_' + method
        args = msg.findall('arg')
        fields, params, values = [], [], []
        ctor = None
        for a in args:
            field = 'arg_' + a.get('name')
            ty = {'int':'int','uint':'int','fixed':'int','fd':'int','string':'str','object':'*i8','new_id':'?*i8','array':'*WLArray'}[a.get('type')]
            if a.get('allow-null') == 'true': ty = '?' + ty
            fields.append(field + ': ' + ty + ';')
            if a.get('type') == 'new_id':
                ctor = a.get('interface')
                values.append(field + ': null')
            else:
                params.append(field + ': ' + ty)
                values.append(field + ': ' + field)
        if args:
            out.append(f'type {prefix}_args = {{ {" ".join(fields)} }};')
            out.append(f'extern {prefix}_marshal(proxy: *i8, opcode: u32, iface: ?*WLInterface@immortal, version: u32, flags: u32, args: *{prefix}_args): ?*i8 = wl_proxy_marshal_array_flags;')
        out.append(prefix + '(proxy: *i8' + (', ' + ', '.join(params) if params else '') + ')' + (': ?*i8' if ctor else '') + ' {')
        if args: out.append(f'    args: {prefix}_args = {prefix}_args {{ {", ".join(values)} }};')
        call = prefix + '_marshal' if args else 'wl_empty_marshal'
        iface = '&' + ctor + '_interface' if ctor else 'null'
        flags = '1u32' if msg.get('type') == 'destructor' else '0u32'
        out.append('    ' + ('' if ctor else '_result: ?*i8 = ') + f'{call}(proxy, {opcode}u32, {iface}, wl_proxy_get_version(proxy), {flags}, ' + ('&args' if args else 'null') + ');')
        out.append('}\n')

out.append('''type WLBindArgs = { name: int; interface: str; version: int; id: ?*i8; };
extern wl_bind_marshal(proxy: *i8, opcode: u32, iface: *WLInterface@immortal, version: u32, flags: u32, args: *WLBindArgs): ?*i8 = wl_proxy_marshal_array_flags;
wl_registry_bind(proxy: *i8, name: u32, iface: *WLInterface@immortal, version: u32): ?*i8 {
    args: WLBindArgs = WLBindArgs { name: name as int, interface: iface.name, version: version as int, id: null };
    wl_bind_marshal(proxy, 0u32, iface, version, 0u32, &args);
}
''')
generated = '\n'.join(out)
if '--check' in sys.argv:
    if (ROOT / 'protocol.l8').read_text() != generated:
        raise SystemExit('protocol.l8 is stale; run python3 programs/wayland/generate.py')
else:
    (ROOT / 'protocol.l8').write_text(generated)
